import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowRight, CircleHelp, FileText, ImageIcon, MapPin, ShieldCheck } from "lucide-react";
import { getPerson } from "@/lib/people";
import { listPublicGalleryRecords } from "@/lib/public-gallery";
import { lifeChapters } from "@/data/knowledge/chapters";

export const dynamic = "force-dynamic";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const person = await getPerson(slug); const reviewedForIndex = Boolean(person && (slug === "saroop-singh" || person.articles.length >= 2)); return { title: person?.name || "Person not found", description: person ? `${person.name} appears in ${person.articles.length} active catalogue entries.` : undefined, alternates: person ? { canonical: `/people/${slug}` } : undefined, robots: reviewedForIndex ? undefined : { index: false, follow: false } }; }
function dateLabel(value?: string, recordedDateText?: string) { if (!value) return recordedDateText || "Date unknown"; const date = new Date(`${value}T00:00:00`); return Number.isNaN(date.getTime()) ? recordedDateText || "Date unknown" : date.toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" }); }

export default async function PersonPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const [person, gallery] = await Promise.all([getPerson(slug), listPublicGalleryRecords()]); if (!person) notFound();
  const isSaroop = slug === "saroop-singh"; const dated = person.articles.filter(article => article.date).sort((a, b) => String(a.date).localeCompare(String(b.date))); const undated = person.articles.filter(article => !article.date); const photographs = isSaroop ? gallery.filter(record => record.familyMember?.includes("Saroop Singh")) : []; const portrait = photographs[0];
  return <main className="min-h-screen bg-[#f6f1e8] text-[#17241d]"><header className="bg-[#17241d] text-[#f8f1e4]"><div className="mx-auto max-w-7xl px-5 py-5 sm:px-8"><Link href="/people" className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-stone-300 hover:text-white"><ArrowLeft className="h-4 w-4" /> All people</Link></div><div className="mx-auto grid max-w-7xl items-end gap-8 px-5 pb-12 pt-5 sm:px-8 sm:pb-16 lg:grid-cols-[1.1fr_.9fr]"> <div><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.2em] text-amber-300"><ShieldCheck className="h-4 w-4" /> {isSaroop ? "Central archive subject" : "Named-source index"}</p><h1 className="mt-5 font-serif text-6xl leading-[.9] sm:text-8xl">{person.name}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-stone-300">{isSaroop ? "The surviving sources document athletics in pre-war Malaya and later records that may name the same man. Each item returns to its newspaper capture and keeps identity uncertainty visible." : `This printed name appears in ${person.articles.length} active catalogue entries. The archive does not assume that every matching label refers to one individual.`}</p><div className="mt-8 flex flex-wrap gap-3 text-sm"><span className="rounded-full bg-white/10 px-4 py-2">{person.articles.length} catalogue mentions</span>{dated[0] && <span className="rounded-full bg-white/10 px-4 py-2">Dated entries: {dated[0].date?.slice(0, 4)}–{dated.at(-1)?.date?.slice(0, 4)}</span>}{photographs.length > 0 && <span className="rounded-full bg-white/10 px-4 py-2">{photographs.length} source images</span>}</div></div>{isSaroop && portrait && <div className="relative aspect-[4/3] overflow-hidden rounded-[2rem] border border-white/10 bg-black"><Image src={portrait.originalImageUrl} alt={portrait.title} fill priority unoptimized sizes="(max-width: 1024px) 100vw, 45vw" className="object-contain" /></div>}</div></header>
    {isSaroop && <section className="mx-auto max-w-7xl px-5 py-12 sm:px-8 sm:py-16"><p className="text-xs font-semibold uppercase tracking-[.18em] text-amber-800">Evidence-backed life chapters</p><div className="mt-6 grid gap-5 lg:grid-cols-2">{lifeChapters.map(chapter => { const article = person.articles.find(item => item.slug === chapter.featuredSlug); return <article key={chapter.id} className="overflow-hidden rounded-[2rem] border border-amber-950/10 bg-white shadow-sm"><div className="grid sm:grid-cols-[.72fr_1.28fr]"><div className="relative min-h-48 bg-stone-200">{article?.image && <Image src={article.image} alt="" fill unoptimized sizes="(max-width: 640px) 100vw, 30vw" className="object-cover" />}</div><div className="p-6"><p className="text-xs font-semibold uppercase tracking-[.16em] text-amber-800">{chapter.years} · {chapter.eyebrow}</p><h2 className="mt-3 font-serif text-3xl leading-none">{chapter.title}</h2><p className="mt-4 text-sm leading-6 text-neutral-600">{chapter.summary}</p><p className="mt-4 text-xs font-semibold text-neutral-500">{chapter.evidence}</p>{article && <Link href={`/articles/${article.slug}`} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-amber-900">Read supporting source <ArrowRight className="h-4 w-4" /></Link>}</div></div></article>; })}</div></section>}
    {photographs.length > 0 && <section className="bg-[#17241d] text-white"><div className="mx-auto max-w-7xl px-5 py-12 sm:px-8 sm:py-16"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.18em] text-amber-300"><ImageIcon className="h-4 w-4" /> Best-available source images identifying Saroop Singh</p><div className="mt-6 grid gap-5 sm:grid-cols-2">{photographs.map(photo => <Link href={`/gallery/${photo.id}`} key={photo.id} className="group overflow-hidden rounded-[2rem] border border-white/10 bg-white/5"><div className="relative aspect-[4/3] bg-black"><Image src={photo.originalImageUrl} alt={photo.title} fill unoptimized sizes="(max-width: 640px) 100vw, 50vw" className="object-contain" /></div><div className="p-5"><h3 className="font-serif text-3xl">{photo.title}</h3><p className="mt-2 text-sm text-stone-400">Date: {photo.date || "unknown"} · {photo.sourceProvenance}</p></div></Link>)}</div></div></section>}
    <section className="mx-auto max-w-5xl px-5 py-12 sm:px-8 sm:py-16"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-amber-800">Primary-source trail</p><h2 className="mt-2 font-serif text-5xl">Newspaper evidence</h2></div><span className="text-sm text-neutral-500">{person.articles.length} records</span></div><div className="mt-7 space-y-4">{[...dated, ...undated].map(article => <Link key={article.slug} href={`/articles/${article.slug}`} className="group grid gap-4 rounded-2xl border border-amber-950/10 bg-white p-4 shadow-sm transition hover:shadow-lg sm:grid-cols-[7rem_1fr_auto] sm:items-center"><div className="relative aspect-[4/3] overflow-hidden rounded-xl bg-stone-100">{article.image && <Image src={article.image} alt="" fill unoptimized sizes="112px" className="object-cover" />}</div><div><p className="text-xs font-semibold uppercase tracking-[.13em] text-amber-800">{dateLabel(article.date, article.date_text)}</p><h3 className="mt-1 font-serif text-2xl leading-tight">{article.title}</h3><div className="mt-2 flex flex-wrap gap-3 text-xs text-neutral-500">{(article.publication || article.source) && <span className="flex items-center gap-1"><FileText className="h-3.5 w-3.5" />{article.publication || article.source}</span>}{article.location && <span className="flex items-center gap-1"><MapPin className="h-3.5 w-3.5" />{article.location}</span>}</div></div><ArrowRight className="hidden h-5 w-5 text-amber-800 transition group-hover:translate-x-1 sm:block" /></Link>)}</div>
      {isSaroop && <div className="mt-10 rounded-2xl border border-dashed border-amber-900/25 bg-amber-50 p-5"><p className="flex items-center gap-2 font-semibold"><CircleHelp className="h-5 w-5" /> Family relationships remain open research</p><p className="mt-2 text-sm leading-6 text-amber-950/75">No reviewed source currently identifies parents, siblings, spouse or children. We will not invent them from surnames or faces. Family testimony can add this missing human layer.</p><Link href="/remember?kind=story" className="mt-4 inline-flex min-h-11 items-center rounded-full bg-[#17241d] px-5 text-sm font-semibold text-white">Add a memory or correction</Link></div>}
    </section></main>;
}
