import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Maximize2, ShieldCheck } from "lucide-react";
import { ArchiveQr } from "@/components/archive-qr";
import { PremiereStats } from "./premiere-stats";
import { absoluteSiteUrl } from "@/lib/site";

export const metadata: Metadata = { title: "Family Premiere", robots: { index: false, follow: false } };
export default function PremierePage() { return <main className="flex min-h-screen items-center bg-[#101713] px-5 py-12 text-[#f8f1e4] sm:px-8"><div className="mx-auto w-full max-w-7xl"><div className="grid items-center gap-10 lg:grid-cols-[1.15fr_.85fr]"><div><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.22em] text-amber-300"><ShieldCheck className="h-4 w-4" /> Saroop Singh Archive · Family Premiere</p><h1 className="mt-5 max-w-4xl font-serif text-6xl leading-[.84] sm:text-8xl">Tonight, the record comes home.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-stone-300">Begin together on the large screen. Then scan with your phone to return a name, photograph or voice to the family archive.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/story" className="flex min-h-14 items-center justify-center gap-2 rounded-full bg-amber-300 px-7 font-bold text-[#17241d]"><Maximize2 className="h-5 w-5" /> Begin full-screen story</Link><Link href="/family-day" className="flex min-h-14 items-center justify-center gap-2 rounded-full border border-white/20 px-7 font-semibold">Invitation kit <ArrowRight className="h-4 w-4" /></Link></div></div><div className="text-center"><ArchiveQr value={absoluteSiteUrl("/remember")} label="Scan to enter the Family Memory Room" size={240} /><p className="mt-5 text-sm text-stone-400">No login · Private review · Any language</p></div></div><div className="mt-12"><p className="mb-4 text-center text-xs font-semibold uppercase tracking-[.2em] text-stone-400">Family contributions · live aggregate</p><PremiereStats /></div></div></main>; }
