import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowRight, FileText, MapPin, ShieldCheck } from "lucide-react";
import { getAllArticles } from "@/lib/articles";
import { ArchiveQr } from "@/components/archive-qr";
import { StoryControls } from "./story-controls";
import { absoluteSiteUrl } from "@/lib/site";

export const metadata: Metadata = { title: "A Life in the Record", description: "A guided family exhibition through the surviving record of Saroop Singh." };

export default async function StoryPage() {
  const articles = await getAllArticles();
  const source = (slug: string) => articles.find(article => article.slug === slug);
  const emergence = source("1936-07-18_straits-times_athletic-results-saroop-singh");
  const record = source("1937-07-18_straits-times_selangor-athletic-meeting-saroop-singh-record");
  const community = source("1949-04-17_indian-daily-mail_first-malayan-sikh-ladies-athletic-meet");
  return <main data-story className="bg-[#101713] text-[#f8f1e4] [scroll-snap-type:y_proximity]">
    <StoryControls />
    <section className="relative flex min-h-[calc(100dvh-4rem)] snap-start items-end overflow-hidden"><Image src="/gallery-images/gemini-saroop-singh-running1-original.jpg" alt="Newspaper crop showing M. Thomas and Saroop Singh after a mile race" fill priority unoptimized sizes="100vw" className="object-cover opacity-55 grayscale" /><div className="absolute inset-0 bg-gradient-to-t from-[#101713] via-[#101713]/45 to-black/25" /><div className="relative mx-auto w-full max-w-7xl px-5 pb-20 sm:px-8 sm:pb-24"><p className="text-xs font-semibold uppercase tracking-[.25em] text-amber-300">A family exhibition</p><h1 className="mt-5 max-w-5xl font-serif text-6xl leading-[.82] sm:text-8xl lg:text-[9rem]">A life in<br />the record.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-stone-300">For decades, the story lived in fragments: a name in newsprint, athletes held in a newspaper photograph, memories kept at home.</p><p className="mt-10 flex items-center gap-2 text-sm text-stone-400">Scroll to begin <ArrowDown className="h-4 w-4 animate-bounce" /></p></div></section>
    <section className="grid min-h-screen snap-start items-center gap-8 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:px-[8vw]"> <div><p className="text-xs font-semibold uppercase tracking-[.2em] text-amber-300">1936 · The first dated result</p><h2 className="mt-4 font-serif text-6xl leading-[.9] sm:text-8xl">A name enters the record.</h2><p className="mt-7 max-w-xl text-lg leading-8 text-stone-300">The Straits Times of 18 July 1936 lists Saroop Singh third in a one-mile result. The clipping mentions V.I.O.B.A.; it does not establish that he was then a student.</p>{emergence && <Link href={`/articles/${emergence.slug}`} className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-full border border-white/20 px-6 font-semibold">Show me the evidence <FileText className="h-4 w-4" /></Link>}</div><div className="relative aspect-[4/3] overflow-hidden rounded-[2rem] bg-white shadow-2xl rotate-1">{emergence?.image && <Image src={emergence.image} alt={emergence.title} fill unoptimized sizes="50vw" className="object-contain p-3" />}</div></section>
    <section className="min-h-screen snap-start bg-amber-300 px-5 py-20 text-[#17241d] sm:px-8 lg:px-[8vw]"><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-[.2em]">July 1937 · The breakthrough</p><div className="mt-7 grid items-center gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><div className="font-mono text-[clamp(5rem,18vw,13rem)] font-bold leading-none tracking-[-.08em]">880</div><p className="mt-2 text-xl font-semibold">yards. One state-record performance.</p><div className="mt-8 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#17241d] p-5 text-white"><p className="text-3xl font-bold">2:06 4/5</p><p className="mt-2 text-xs text-stone-300">Two direct result reports</p></div><div className="rounded-2xl border border-[#17241d]/20 bg-white/50 p-5"><p className="text-3xl font-bold">2:05 4/5</p><p className="mt-2 text-xs">Implied by a later roundup</p></div></div><p className="mt-5 text-sm leading-6 text-amber-950/70">Two direct reports give 2:06 4/5. A later Morning Tribune roundup says one second was removed from 2:06 4/5, implying 2:05 4/5. The record performance is supported; the exact time remains a documented conflict.</p></div><div className="relative aspect-[4/3] overflow-hidden rounded-[2rem] bg-white shadow-2xl">{record?.image && <Image src={record.image} alt={record.title} fill unoptimized sizes="55vw" className="object-contain p-3" />}</div></div>{record && <Link href={`/articles/${record.slug}`} className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-full bg-[#17241d] px-6 font-semibold text-white">Read the supporting report <ArrowRight className="h-4 w-4" /></Link>}</div></section>
    <section className="grid min-h-screen snap-start items-center gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[1.1fr_.9fr] lg:px-[8vw]"><div className="relative aspect-[4/3] overflow-hidden rounded-[2rem] border border-white/10 bg-black"><Image src="/gallery-images/saroop-singh-running2.png" alt="Newspaper portrait identifying Saroop Singh as the half-mile winner" fill unoptimized sizes="55vw" className="object-contain" /><span className="absolute bottom-4 left-4 rounded-full bg-emerald-950/90 px-4 py-2 text-xs font-semibold uppercase tracking-[.15em]">Source crop · 19 July 1937</span></div><div><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.2em] text-amber-300"><ShieldCheck className="h-4 w-4" /> The source remains the authority</p><h2 className="mt-5 font-serif text-6xl leading-[.9] sm:text-8xl">Not remade.<br />Returned to view.</h2><p className="mt-7 text-lg leading-8 text-stone-300">AI experiments can help us examine damage, but they cannot recover certainty the source does not contain. This crop is preserved as published in the 1937 newspaper record; no derivative may replace it.</p></div></section>
    <section className="min-h-screen snap-start bg-[#f6f1e8] px-5 py-20 text-[#17241d] sm:px-8 lg:px-[8vw]"><div className="mx-auto max-w-7xl"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.2em] text-amber-800"><MapPin className="h-4 w-4" /> Where the record places him</p><h2 className="mt-5 max-w-4xl font-serif text-6xl leading-[.9] sm:text-8xl">Across Malaya, a sporting life becomes visible.</h2><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{["Kuala Lumpur", "Seremban", "Selangor", "Singapore"].map((place, index) => <div key={place} className="rounded-[2rem] border border-amber-950/10 bg-white p-6"><p className="text-6xl font-serif text-amber-800/25">0{index + 1}</p><h3 className="mt-6 font-serif text-3xl">{place}</h3><p className="mt-3 text-sm leading-6 text-neutral-600">A place named in the surviving newspaper collection—not a claim about residence.</p></div>)}</div></div></section>
    <section className="grid min-h-screen snap-start items-center gap-10 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:px-[8vw]"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-amber-300">1949 · The story widens</p><h2 className="mt-5 font-serif text-6xl leading-[.9] sm:text-8xl">From individual competition to community sport.</h2><p className="mt-7 text-lg leading-8 text-stone-300">Post-war reporting associates Saroop Singh with the first Malayan Sikh Ladies Athletic Meet. The paper record now touches a wider Sikh sporting community.</p>{community && <Link href={`/articles/${community.slug}`} className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-full border border-white/20 px-6 font-semibold">Open the source <FileText className="h-4 w-4" /></Link>}</div><div className="relative aspect-[4/3] overflow-hidden rounded-[2rem] bg-white">{community?.image && <Image src={community.image} alt={community.title} fill unoptimized sizes="50vw" className="object-contain p-3" />}</div></section>
    <section className="relative flex min-h-screen snap-start items-center overflow-hidden px-5 py-20 sm:px-8 lg:px-[8vw]"><Image src="/gallery-images/gemini-extended-family-portrait-1970s-group-original.jpg" alt="Extended family group portrait with people not yet identified" fill unoptimized sizes="100vw" className="object-cover opacity-25" /><div className="absolute inset-0 bg-[#101713]/70" /><div className="relative mx-auto max-w-5xl text-center"><p className="text-xs font-semibold uppercase tracking-[.2em] text-amber-300">The record is unfinished</p><h2 className="mt-6 font-serif text-6xl leading-[.9] sm:text-8xl">Who can you return a name to?</h2><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-stone-300">Newspapers preserve public results. Families preserve voices, nicknames, relationships and the meaning of a day. The archive needs both—and never confuses one for the other.</p><Link href="/remember" className="mt-9 inline-flex min-h-12 items-center gap-2 rounded-full bg-amber-300 px-7 font-semibold text-[#17241d]">Enter the Family Memory Room <ArrowRight className="h-4 w-4" /></Link></div></section>
    <section className="flex min-h-screen snap-start items-center justify-center bg-amber-300 px-5 py-20 text-center text-[#17241d]"><div><h2 className="mx-auto max-w-5xl font-serif text-6xl leading-[.88] sm:text-8xl">This archive is unfinished because memory still lives with you.</h2><div className="mt-10"><ArchiveQr value={absoluteSiteUrl("/remember")} label="Scan to add a name, photograph, correction, or voice memory" /></div><p className="mt-8 text-sm font-semibold">No account. Nothing published without review.</p><Link href="/" className="mt-8 inline-flex min-h-12 items-center rounded-full border border-[#17241d]/30 px-6 font-semibold">Return to the archive</Link></div></section>
  </main>;
}
